spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rpgstats}
    username: ${SPRING_DATASOURCE_USERNAME:compose-postgres}
    password: ${SPRING_DATASOURCE_USERNAME:compose-postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql