spring:
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: none
  main:
    allow-circular-references: true
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.xml
server:
  servlet:
    context-path: /api/v1
  error:
    include-message: always
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
springdoc:
  override-with-generic-response: false
